version: "3.8"
services:

  traefik:
    container_name: docker_traefik
    image: traefik:v2.3
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik_global"
    ports:
      - "80:80" #all traffic will arrive through this port
      - "8080:8080" #traefik dashboard/api
    volumes:
      #this is how traefik reads docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik

networks:
  traefik:
    name: traefik_global
