version: "3.8"
services:

  www:
    build: php
    container_name: www_site1
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - traefik # add 1st so traefik performs better
      - site1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.site1_com.rule=Host(`site1.localhost`)"
      - "traefik.http.services.site1_com.loadbalancer.server.port=80"

networks:
  site1:
  traefik:
    external:
      name: traefik_global
